name: 🚀 Deploy nodejs directory on push with FTP

on:
  push:
    branches:
      - master
    paths:
      - "nodejs/**"

jobs:
  deploy_created_vue2_ui:
    name: 🎉 Deploy vue2-ui to langnang.byethost32.com
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Create Vue@2 App
        run: |
          npm install -g @vue/cli
          cd nodejs
          vue create created-vue2-ui -d --merge

      - name: Install && Build
        run: |
          cp nodejs/vue2-ui nodejs/created-vue2-ui
          cd nodejs/created-vue2-ui
          yarn install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b32_28202196
          # ftp password
          password: ${{ secrets.ftp_password }}
          # local dir
          local-dir: ./nodejs/created-vue2-ui/dist/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /htdocs/frameworks/nodejs/vue2-ui/
          # File to Exclude
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**

deploy_created_vuepress_docs:
  name: 🎉 Deploy vuepress-docs to langnang.byethost32.com
  runs-on: ubuntu-latest
  steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Create VuePress App
      run: |
        npm install -g @vue/cli
        cd nodejs
        yarn create vuepress vuepress-docs

    - name: Install && Build
      run: |
        cd nodejs/vuepress-docs
        yarn install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        # ftp server
        server: ftpupload.net
        # ftp username
        username: b32_28202196
        # ftp password
        password: ${{ secrets.ftp_password }}
        # local dir
        local-dir: ./nodejs/vuepress-docs/dist/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: /htdocs/frameworks/nodejs/vuepress-docs/
        # File to Exclude
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
          **/node_modules/**
